name: daily
on:
  workflow_dispatch
  schedule:
    - cron: '00 16 * * *'

jobs:
  run-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Fetch data and analyze
        run: ./gradlew run analyze -Dsince=2015-01-01
